### ISSUE TITLE
Issue with derivative calculation on first update

### ISSUE THREAD

**Issue by blockypixel** [vazgriz/PID_Controller#1]
First off - thanks for the clean implementation and fantastic article. It helped clear up a lot of things for me.

I have noticed a small issue with the update however. When calculating the derivative, it doesn't wait for the first value to be set before calculating the rate of change, meaning the first update will always be `(current - 0) / dt`.

I've updated my local copy to only calculate D after at least one update has been called so it has a point of reference, and that seems to have done the trick

**Comment by vazgriz** [comment]
Good catch
