### ISSUE TITLE
Error in UpdateAngle function

### ISSUE THREAD

**Issue by srslylawl** [vazgriz/PID_Controller#2]
There seems to be an issue in the PIDController.cs on line 79:

![image](https://github.com/vazgriz/PID_Controller/assets/58690303/e061cab2-6e92-40e6-b778-67dd4a3ef831)

The errorLast value immediately gets set to the current error value, basically eliminating the derivative completely. Deleting this line should fix the issue.

Also - i feel like UpdateAngle should just call Update using the remapped angles, saving duplicate code, no?

Thanks for the script and video explanation, great stuff!

**Comment by vazgriz** [comment]
Thanks for catching this
